config/routes.rb
Rails.application.routes.draw do
  root "gold_places#index"
  resources :schedules
  resources :plans
  resources :gold_places
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gold_place.rb
class GoldPlace < ApplicationRecord
  has_many :gold_plans
  has_many :plans, through: :gold_plans,source: :plan
end

app/models/gold_plan.rb
class GoldPlan < ApplicationRecord
  belongs_to :gold_place
  belongs_to :plan
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plan_schedule
  has_many :schedules, through: :plan_schedule
  has_many :gold_plans
  has_many :gold_places, through: :gold_plans, :source => "gold_place"
  accepts_nested_attributes_for :schedules
end

app/models/plan_schedule.rb
class PlanSchedule < ApplicationRecord
  belongs_to :plan
  belongs_to :schedule
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :plan_schedule
  has_many :plans, through: :plan_schedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gold_places_controller.rb
class GoldPlacesController < ApplicationController
  before_action :set_gold_place, only: [:show, :edit, :update, :destroy]

  # GET /gold_places
  # GET /gold_places.json
  def index
    @gold_places = GoldPlace.all
  end

  # GET /gold_places/1
  # GET /gold_places/1.json
  def show
  end

  # GET /gold_places/new
  def new
    @gold_place = GoldPlace.new
  end

  # GET /gold_places/1/edit
  def edit
  end

  # POST /gold_places
  # POST /gold_places.json
  def create
    @gold_place = GoldPlace.new(gold_place_params)

    respond_to do |format|
      if @gold_place.save
        format.html { redirect_to @gold_place, notice: 'Gold place was successfully created.' }
        format.json { render :show, status: :created, location: @gold_place }
      else
        format.html { render :new }
        format.json { render json: @gold_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gold_places/1
  # PATCH/PUT /gold_places/1.json
  def update
    respond_to do |format|
      if @gold_place.update(gold_place_params)
        format.html { redirect_to @gold_place, notice: 'Gold place was successfully updated.' }
        format.json { render :show, status: :ok, location: @gold_place }
      else
        format.html { render :edit }
        format.json { render json: @gold_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gold_places/1
  # DELETE /gold_places/1.json
  def destroy
    @gold_place.destroy
    respond_to do |format|
      format.html { redirect_to gold_places_url, notice: 'Gold place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold_place
      @gold_place = GoldPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gold_place_params
      params.require(:gold_place).permit(:name, :prefecture)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @schedules = Schedule.all
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    debugger
    @plan = Plan.new(plan_params)
    @plan.gold_places << GoldPlace.find(params[:plan][:gold_place_ids])
    @plan.schedules << Schedule.create(start_time: params[:plan][:start_time], end_time: params[:plan][:end_time])
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :price)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    @schedule.plans << Plan.find(params[:schedule][:plan_ids])
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gold_places_helper.rb
module GoldPlacesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/gold_places/_form.html.erb
<%= form_with(model: gold_place, local: true) do |form| %>
  <% if gold_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gold_place.errors.count, "error") %> prohibited this gold_place from being saved:</h2>

      <ul>
      <% gold_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :prefecture %>
    <%= form.text_field :prefecture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gold_places/edit.html.erb
<h1>Editing Gold Place</h1>

<%= render 'form', gold_place: @gold_place %>

<%= link_to 'Show', @gold_place %> |
<%= link_to 'Back', gold_places_path %>

app/views/gold_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gold Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prefecture</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gold_places.each do |gold_place| %>
      <tr>
        <td><%= gold_place.name %></td>
        <td><%= gold_place.prefecture %></td>
        <%gold_place.plans.each do |plan|%>
         <td><%= link_to plan.name, "plans/#{plan.id}"%></td>
         <td><%= plan.price %></td>
        <%end%>
      </tr>
      <tr>
        <td><%= link_to 'Show', gold_place %></td>
        <td><%= link_to 'Edit', edit_gold_place_path(gold_place) %></td>
        <td><%= link_to 'Destroy', gold_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gold Place', new_gold_place_path %>

app/views/gold_places/new.html.erb
<h1>New Gold Place</h1>

<%= render 'form', gold_place: @gold_place %>

<%= link_to 'Back', gold_places_path %>

app/views/gold_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gold_place.name %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @gold_place.prefecture %>
</p>

<%= link_to 'Edit', edit_gold_place_path(@gold_place) %> |
<%= link_to 'Back', gold_places_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <%= form.fields_for :started_at do |s| %>
    <div class="field">
    <%= s.label :開始時間 %>
    <%= s.datetime_select :start_time %>
    <div class="field">
    <%= s.label :終了時間 %>
    <%= s.datetime_select :end_time %>
  </div>

  <%end%>
  <div class="field">
    <%= form.label :ゴルフ場 %>
    <%= form.select :gold_place_ids,  GoldPlace.all.map{ |gp| [gp.name, gp.id]} %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>ゴルフ場</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
         <%unless plan.gold_places.count == 0 %>
        <td><%= plan.gold_places.first.name %></td>
        <%end%>
        <td><%= plan.price %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plan.price %>
</p>
 
  <%= month_calendar events: @plan.schedules  do |date, meetings| %>

  <%= date %>

  <% meetings.each do |meeting| %>
 
    <div class="saasas">
      <%= meeting.start_time %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

   <%= form.hidden_field :plan_ids , value: [1] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.name %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @schedule.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>